"""Public-score-only descriptive export and small manuscript integration.

Run: python -B scripts/build_png_context_addendum.py
No model/application imports, private rows, keys, packets or execution ledgers.
Existing AUC estimates/intervals are read unchanged, never recomputed or refitted.
"""
import csv
import hashlib
import json
import math
import os
from pathlib import Path
import statistics
import subprocess

os.environ.setdefault("MPLCONFIGDIR", "/tmp/imagecalgacus-addendum-mpl")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT/"artifacts/png_context_detection_review"
OUT = ROOT/"artifacts/png_context_detection_addendum"
PAPER = ROOT/"paper/results"
FIELD = "surprisal_bits_mean"
UNITS = "bits per delivered RGB channel value"
CATEGORIES = ("ordinary", "fixed", "gated", "arithmetic")
NAMES = dict(ordinary="Ordinary controls", fixed="Fixed rank",
             gated="Entropy gated", arithmetic="Arithmetic A1")
# Publication package: scripts/build_publication_results.py COLORS/style().
# Repeated here to avoid importing its application/accounting dependencies.
COLORS = dict(ordinary="#666666", fixed="#0072B2", gated="#009E73", arithmetic="#D55E00")
GENERATED = "<!-- Generated by scripts/build_png_context_addendum.py -->\n"


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def snapshot_public_evidence():
    # Reporting guard only: neither private runs nor private ledgers are read.
    paths = [p for folder in (ROOT/"artifacts").iterdir() if folder.is_dir() and folder != OUT
             for p in folder.rglob("*") if p.is_file()]
    paths += [ROOT/"notes/png_context_detection.md", ROOT/"scripts/build_publication_results.py"]
    return {str(p.relative_to(ROOT)): digest(p) for p in sorted(paths)}


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.parent == PAPER and path.exists() and not path.read_text().startswith(GENERATED):
        raise ValueError("refusing to replace an independently edited manuscript file: "+str(path))
    path.write_text(text, encoding="utf-8")


def csv_write(path, rows):
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def load_observations():
    manifest, analysis = read(SOURCE/"manifest.json"), read(SOURCE/"analysis.json")
    rows = [json.loads(line) for line in (SOURCE/"results.jsonl").read_text().splitlines()]
    expected = {r["artifact_id"]:r for r in manifest["artifacts"]}
    lookup = {r["artifact_id"]:r for r in rows}
    if len(rows) != 80 or len(lookup) != 80 or set(lookup) != set(expected):
        raise ValueError("missing, duplicate or unexpected PNG observation")
    groups = [g["id"] for g in manifest["groups"]]
    if len(groups) != 20 or len(set(groups)) != 20:
        raise ValueError("exactly 20 frozen groups required")
    if len({r["carrier_sha256"] for r in rows}) != 80:
        raise ValueError("expected the accepted 80 unique PNG identities")
    offsets = np.linspace(-.30, .22, len(groups))
    observations = []
    for category in CATEGORIES:
        for ordinal, group in enumerate(groups):
            selected = [r for r in rows if r["payload_group"] == group and
                        ("ordinary" if r["kind"] == "control" else r["method"]) == category]
            if len(selected) != 1:
                raise ValueError("each category must contain one artifact per group")
            r = selected[0]
            for key, value in expected[r["artifact_id"]].items():
                if r[key] != value:
                    raise ValueError("changed frozen artifact/control association: "+key)
            if not r["scorable"] or r["failure_stage"] or r["failure_reason"] or r["scored_channels"] != 2976:
                raise ValueError("do not silently drop an unscorable accepted artifact")
            if r["context_sha256"] != manifest["contexts"]["row2"]["sha256"]:
                raise ValueError("mismatched row identity")
            for condition in ("correct_scores", "mismatch_scores"):
                if r[condition]["positions"] != 2976 or not math.isfinite(r[condition][FIELD]):
                    raise ValueError("complete finite whole-carrier score required")
            control = lookup[r["control_id"]]
            if control["kind"] != "control" or control["payload_group"] != group or control["control_id"] != control["artifact_id"]:
                raise ValueError("control must be the original, within-group shared artifact")
            old, new = r["correct_scores"][FIELD], r["mismatch_scores"][FIELD]
            observations.append(dict(artifact_id=r["artifact_id"], category=category,
                payload_group=group, group_ordinal=ordinal+1, matched_control_id=r["control_id"],
                carrier_sha256=r["carrier_sha256"], row1_mean_surprisal=old,
                row2_mean_surprisal=new, score_change=new-old, units=UNITS,
                plot_horizontal_offset=float(offsets[ordinal]),
                row1_fixed_minus_matched_control=(old-control["correct_scores"][FIELD] if category=="fixed" else ""),
                row2_fixed_minus_matched_control=(new-control["mismatch_scores"][FIELD] if category=="fixed" else "")))
    if len({r["matched_control_id"] for r in observations}) != 20:
        raise ValueError("controls must be counted once, not once per method")
    return observations, manifest, analysis


def summarize(observations):
    summary = []
    for category in CATEGORIES:
        group = [r for r in observations if r["category"] == category]
        if len(group) != 20:
            raise ValueError("category count changed")
        item = dict(category=category, category_label=NAMES[category], n_artifacts=len(group),
            mean_row1=statistics.fmean(r["row1_mean_surprisal"] for r in group),
            mean_row2=statistics.fmean(r["row2_mean_surprisal"] for r in group),
            mean_score_change=statistics.fmean(r["score_change"] for r in group),
            median_score_change=statistics.median(r["score_change"] for r in group), units=UNITS)
        # Independent reporting identity; not a tolerance on model probability equivalence.
        if not math.isclose(item["mean_score_change"], item["mean_row2"]-item["mean_row1"], abs_tol=1e-12):
            raise ValueError("mean within-artifact subtraction disagrees")
        summary.append(item)
    fixed = [r for r in observations if r["category"] == "fixed"]
    gap = dict(n_paired_groups=len(fixed), units=UNITS,
        row1=statistics.fmean(r["row1_fixed_minus_matched_control"] for r in fixed),
        row2=statistics.fmean(r["row2_fixed_minus_matched_control"] for r in fixed))
    gap["change"] = gap["row2"]-gap["row1"]
    if not math.isclose(gap["change"], summary[1]["mean_score_change"]-summary[0]["mean_score_change"], abs_tol=1e-12):
        raise ValueError("paired control-gap change disagrees with category changes")
    return summary, gap


def make_figure(observations, summary):
    plt.rcParams.update({"font.family":"DejaVu Sans", "font.size":9,
        "axes.titlesize":10, "axes.labelsize":9, "xtick.labelsize":8, "ytick.labelsize":8,
        "legend.fontsize":8, "axes.spines.top":False, "axes.spines.right":False,
        "axes.linewidth":.7, "figure.facecolor":"white", "axes.facecolor":"white",
        "pdf.fonttype":42, "svg.fonttype":"none", "svg.hashsalt":"png-context-score-shifts-v1"})
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    changes = [r["score_change"] for r in observations]
    lower, upper = min(0., min(changes)), max(0., max(changes))
    span = max(.1, upper-lower)
    plotted = {}
    for i, category in enumerate(CATEGORIES):
        group = [r for r in observations if r["category"] == category]
        x = [i+r["plot_horizontal_offset"] for r in group]
        ax.scatter(x, [r["score_change"] for r in group], s=12, color=COLORS[category],
                   edgecolors="white", linewidths=.25, zorder=3)
        mean = summary[i]["mean_score_change"]
        # Mean is offset from every individual point; it cannot hide an observation.
        ax.scatter([i+.36], [mean], marker="D", s=42, facecolors="white",
                   edgecolors="black", linewidths=1.1, zorder=4)
        text = f"mean {mean:+.3f}"
        ax.text(i, upper+.15*span, text, ha="center", va="bottom", fontsize=9)
        plotted[category] = dict(points=len(group), mean=mean, annotation=text,
                                group_order=[r["payload_group"] for r in group])
    ax.axhline(0, color=".4", linestyle="--", linewidth=.8, zorder=1)
    ax.set(xlim=(-.55, 3.60), ylim=(lower-.05*span, upper+.26*span),
        xticks=range(4), xticklabels=["Ordinary\ncontrols","Fixed\nrank","Entropy\ngated","Arithmetic\nA1"],
        ylabel="Change in mean surprisal\n(bits per delivered RGB channel value)")
    ax.grid(axis="y", alpha=.15)
    ax.set_axisbelow(True)
    ax.set_title("Within-PNG score changes: mismatched row2 − correct row1", loc="left", pad=14)
    handles=[Line2D([],[],marker="o",ls="",color=".45",markersize=3,label="Individual PNG"),
             Line2D([],[],marker="D",ls="",markerfacecolor="white",markeredgecolor="black",markersize=5,label="Category mean")]
    fig.legend(handles=handles,loc="lower center",bbox_to_anchor=(.54,.075),ncol=2,frameon=False)
    fig.text(.54,.025,"20 PNGs per category · 20 shared payload groups · descriptive, post hoc",ha="center",fontsize=8)
    fig.subplots_adjust(left=.14,right=.98,top=.86,bottom=.28)
    fig.canvas.draw()
    # Inspect every text object's bounds, excluding automatic ticks outside the axis.
    renderer=fig.canvas.get_renderer()
    hidden=set()
    for axis in (ax.xaxis,ax.yaxis):
        lo,hi=sorted(axis.get_view_interval())
        for tick in axis.get_major_ticks()+axis.get_minor_ticks():
            if not lo<=tick.get_loc()<=hi:hidden.update((id(tick.label1),id(tick.label2)))
    for item in fig.findobj(matplotlib.text.Text):
        if item.get_visible() and item.get_text() and id(item) not in hidden:
            bounds=item.get_window_extent(renderer)
            if bounds.width and bounds.height and (bounds.x0<0 or bounds.y0<0 or bounds.x1>fig.bbox.x1 or bounds.y1>fig.bbox.y1):
                raise ValueError("clipped figure text: "+item.get_text())
    for extension in ("pdf","svg","png"):
        metadata=({"Title":"Descriptive within-PNG score shifts","CreationDate":None,"ModDate":None}
                  if extension=="pdf" else {"Date":None} if extension=="svg" else {})
        fig.savefig(OUT/("score_shifts."+extension),dpi=450,metadata=metadata)
    plt.close(fig)
    return plotted


CAPTION = """**Figure S3 (provisional). Descriptive within-PNG score changes under a mismatched conditioning row.**
Each point is the same artifact's row2 minus row1 whole-carrier mean-surprisal score, in bits per delivered RGB channel value—not a change in AUC. All 80 points (20 ordinary controls, 20 fixed-rank, 20 gated and 20 arithmetic A1 PNGs) come from retained observations in the context-detection experiment. Categories share the same 20 payload groups; each group's ordinary control is counted once and shared across methods. Horizontal offsets follow frozen group order and serve only to separate points. Open black diamonds and annotations show category means; the dashed line marks zero score change. Row2 is the previously frozen random-RGB conditioning row, whereas row1 came from a generated image. This descriptive, post hoc analysis adds no confidence intervals, tests or observations. Mean changes illustrate score movement; AUC depends on the full score rankings. The plot neither establishes security nor isolates a causal mechanism for the AUC changes.
"""


def integration(summary, gap, analysis):
    cell={(c["method"],c["score"]):c for c in analysis["cells"]}
    f,g,a=(cell[m,FIELD] for m in ("fixed","gated","arithmetic"))
    rank=cell["fixed","log_rank_mean"]
    def ci(values):return "["+", ".join(f"{v:.4f}" for v in values)+"]"
    root="../../artifacts"
    text=GENERATED+f"""# PNG conditioning mismatch: manuscript-ready results component

This is a compact integration component, not a complete manuscript. Figure/table numbers below extend the existing publication index provisionally; stable labels are supplied for later typesetting. [Results index](README.md).

## Methods

The context-detection experiment evaluated the same 60 held-out stego PNGs (20 per method) and 20 ordinary PNG controls with an observer knowing the exact PixelCNN++ model and scoring procedure. Correct-context row1 scores were retained from V2; the mismatched observer used the previously frozen development row2. Row1 was the first row of a generated image; row2 comprised random RGB values, frozen before this comparison. Each score is the mean eligible-distribution surprisal over all 2,976 delivered RGB channel values; mean log2 rank is the retained secondary score. Higher scores indicate stego throughout. The accepted 95% AUC/change intervals used 2,000 length-stratified resamples of the 20 payload groups, jointly preserving both observer conditions, methods and shared controls. Each ordinary control is counted once, not as three independent method-specific controls.

For the present descriptive post hoc addition, we subtracted each artifact's correct-context score from its mismatched-context score. We report category means and medians and the mean fixed-minus-control score gap, calculated within the original payload/control groups. We add no tests, confidence intervals, fitted thresholds, inference passes or transmissions.

## Results

The primary fixed-rank AUC decreased from {f['correct_auc']:.4f} to {f['mismatch_auc']:.4f}, with paired change {f['difference']:.4f} and accepted 95% interval {ci(f['difference_95_interval'])} ([Figure 5](#fig-png-context-auc)). Gated AUC changed from {g['correct_auc']:.4f} to {g['mismatch_auc']:.4f} ({g['difference']:+.4f}, {ci(g['difference_95_interval'])}); arithmetic A1 changed from {a['correct_auc']:.4f} to {a['mismatch_auc']:.4f} ({a['difference']:+.4f}, {ci(a['difference_95_interval'])}). Gated and A1 changes remain uncertain. Under mismatch the fixed-rank primary interval {ci(f['mismatch_95_interval'])} only narrowly excludes 0.5; its secondary rank-score interval {ci(rank['mismatch_95_interval'])} includes 0.5 ([Table S2](#tab-png-context-scores)). A clear change for one method and an uncertain change for another do not by themselves establish a difference between the methods' sensitivities.

Across 20 artifacts per category, mean score changes were {summary[0]['mean_score_change']:+.3f} for ordinary controls, {summary[1]['mean_score_change']:+.3f} for fixed rank, {summary[2]['mean_score_change']:+.3f} for gating and {summary[3]['mean_score_change']:+.3f} for A1, in bits per delivered RGB channel value ([Figure S3](#fig-png-score-shifts); [descriptive summary]({root}/png_context_detection_addendum/score_shift_summary.md)). The paired mean fixed-minus-control gap narrowed from {gap['row1']:.6f} to {gap['row2']:.6f} (change {gap['change']:+.6f}). Larger mean score increases for controls than fixed-rank carriers are consistent with this narrowed gap. These descriptive means do not prove why AUC changed: AUC depends on the full score rankings.

## Limitations

This is one specified context mismatch with one known model. Because row1 came from a generated image and row2 from random RGB values, it does not separate context correctness from every difference in row statistics. The observations are repeated measurements of existing carriers in 20 shared payload groups, not additional independent transmissions. The post hoc mean shifts do not establish an independently confirmed mechanism or a between-method sensitivity difference. The accepted AUC intervals are exploratory; neither a near-chance AUC nor context dependence establishes cryptographic secrecy, broad resistance to detection or resistance to fully blind/model-independent observers.

## Main Results figure

<a id="fig-png-context-auc"></a>

### Figure 5: Correct versus mismatched PNG observer context

![Accepted context-AUC comparison]({root}/png_context_detection_review/context_auc.png)

[PDF]({root}/png_context_detection_review/context_auc.pdf) · [SVG]({root}/png_context_detection_review/context_auc.svg). Stable manuscript label: `fig:png-context-auc`.

**Caption.** Accepted primary mean-surprisal AUCs under correct row1 and mismatched row2 (A), with paired changes, row2 minus row1 (B). The same 60 stego PNGs and 20 shared ordinary controls are used in both conditions. Whiskers are the original grouped 95% intervals from 2,000 length-stratified payload-group draws, preserving both conditions, all methods and shared controls. The observer knows the exact model and scoring procedure. Higher score always means stego; no AUC orientation or classification threshold is selected here. The dotted lines mark 0.5 AUC and zero change, not fitted thresholds. This existing figure is reused unchanged; its findings do not establish security.

## Supplementary material

<a id="fig-png-score-shifts"></a>

### Figure S3: Descriptive score shifts

![Within-artifact score changes]({root}/png_context_detection_addendum/score_shifts.png)

[PDF]({root}/png_context_detection_addendum/score_shifts.pdf) · [SVG]({root}/png_context_detection_addendum/score_shifts.svg). Stable manuscript label: `fig:png-score-shifts`.

{CAPTION}

<a id="tab-png-context-scores"></a>

### Table S2: Full primary and secondary context-detection comparison

[Accepted Markdown table]({root}/png_context_detection_review/comparison.md) · [LaTeX]({root}/png_context_detection_review/comparison.tex) · [unrounded CSV]({root}/png_context_detection_review/comparison.csv). Stable manuscript label: `tab:png-context-scores`.

**Caption.** Original correct/mismatched AUCs, grouped intervals and paired changes for whole-carrier mean surprisal and mean log2 rank. Each cell has 20 scorable stego PNGs and 20 unique matched controls; the same controls are shared across methods and conditions. These are repeated score measurements, not new recovery observations. Existing score orientation, group resampling and numerical results are unchanged.

## Reproduction and sources

`python -B scripts/build_png_context_addendum.py` reads only public retained evidence and uses the existing NumPy/Matplotlib plotting stack. No weights, raw contexts, keys, packets or execution ledgers are required. [Addendum/provenance]({root}/png_context_detection_addendum/README.md) · [Accepted detection evidence]({root}/png_context_detection_review/README.md) · [Existing publication index]({root}/publication_results/README.md). New GPU usage for this reporting addition: **0 seconds**.
"""
    write(PAPER/"png_context_detection.md",text)
    write(PAPER/"README.md",GENERATED+"""# Manuscript results integration index

No manuscript source or manuscript build was present at this checkpoint. These are small manuscript-ready components, not a complete paper. Existing experimental packets and publication exports remain unchanged. Numbers are provisional until a manuscript layout is chosen; stable labels avoid ambiguous cross-references.

| Placement | Item | Source / integration |
|---|---|---|
| Existing main and supplementary results | Figures 1–4, S1–S2; Tables 1–4, S1 | [Accepted publication index](../../artifacts/publication_results/README.md) |
| Main Results | Figure 5: PNG context-AUC comparison | [Detection subsection and figure](png_context_detection.md#fig-png-context-auc); label `fig:png-context-auc` |
| Supplementary | Figure S3: descriptive within-PNG score shifts | [Figure and caption](png_context_detection.md#fig-png-score-shifts); label `fig:png-score-shifts` |
| Supplementary | Table S2: full primary/secondary AUC comparison | [Accepted table and caption](png_context_detection.md#tab-png-context-scores); label `tab:png-context-scores` |

[Methods, Results and limitations](png_context_detection.md) · [New descriptive data/figure package](../../artifacts/png_context_detection_addendum/README.md).

Rebuild the retained-score addition and these generated integration components:

```sh
python -B scripts/build_png_context_addendum.py
```

This uses only public scores/metadata and the existing plotting dependencies. It does not execute models or access private contexts, keys or ledgers. Manuscript compilation is not applicable until a manuscript exists; the supplementary figure's PDF is rendered and inspected separately.
""")


def main():
    before=snapshot_public_evidence()
    inputs=[SOURCE/name for name in ("results.jsonl","manifest.json","analysis.json",
        "accounting.json","context_auc.pdf","context_auc.svg","context_auc.png",
        "comparison.csv","comparison.md","comparison.tex","captions.md","README.md")]
    inputs += [ROOT/"notes/png_context_detection.md",ROOT/"artifacts/publication_results/README.md",
               ROOT/"scripts/build_publication_results.py"]
    input_hashes={str(p.relative_to(ROOT)):digest(p) for p in inputs}
    observations,manifest,analysis=load_observations()
    summary,gap=summarize(observations)
    OUT.mkdir(parents=True,exist_ok=True)
    csv_write(OUT/"score_shift_observations.csv",observations)
    csv_write(OUT/"score_shift_summary.csv",summary)
    plotted=make_figure(observations,summary)
    write(OUT/"caption.md",CAPTION)
    table="| Category | Artifacts | Row1 mean | Row2 mean | Mean change | Median change |\n|---|---:|---:|---:|---:|---:|\n"
    table+="\n".join(f"| {s['category_label']} | {s['n_artifacts']} | {s['mean_row1']:.3f} | {s['mean_row2']:.3f} | {s['mean_score_change']:+.3f} | {s['median_score_change']:+.3f} |" for s in summary)
    write(OUT/"score_shift_summary.md","# Descriptive PNG score shifts\n\n"+table+
        f"\n\nAll score values use {UNITS}. Changes are within-artifact row2 minus row1. These are descriptive, post hoc means/medians, not AUC changes or new inferential results.\n\n"
        f"The mean fixed-rank-minus-control gap, paired within the original 20 groups, is **{gap['row1']:.6f}** under row1 and **{gap['row2']:.6f}** under row2: change **{gap['change']:+.6f}**. Controls are counted once and shared across methods. Unrounded paired gaps are retained in the fixed-rank rows of the observations CSV.\n")
    integration(summary,gap,analysis)
    write(OUT/"README.md",f"""# Descriptive PNG score-shift addendum

One supplementary figure and a descriptive table from **all 80 retained PNG observations**, with 20 artifacts in each category and 20 shared payload groups. No new inference, observations, contexts, tests of hypotheses or confidence intervals.

![Descriptive within-artifact score changes](score_shifts.png)

[PDF](score_shifts.pdf) · [SVG](score_shifts.svg) · [450-dpi PNG](score_shifts.png) · [Caption](caption.md)

{table}

Units: {UNITS}. The paired mean fixed-rank-minus-control gap narrows from **{gap['row1']:.6f}** to **{gap['row2']:.6f}** (change **{gap['change']:+.6f}**). Higher control score increases are consistent with this narrowing; descriptive mean shifts do not independently explain why AUC changed, which depends on full score rankings.

## Data, provenance and integration

- [All 80 observations, original group/control links and paired gaps](score_shift_observations.csv)
- [Summary CSV](score_shift_summary.csv), [Markdown](score_shift_summary.md)
- [Input/script/output identities and focused checks](provenance.json)
- [Manuscript results index](../../paper/results/README.md), [Methods/Results/limitations component](../../paper/results/png_context_detection.md)
- Main Figure 5 reuses the [accepted context-AUC figure](../png_context_detection_review/context_auc.pdf) unchanged. Supplementary Figure S3 is this score-shift figure; supplementary Table S2 reuses the [full accepted primary/secondary AUC table](../png_context_detection_review/comparison.md). Numbering is provisional because no manuscript existed.

The fixed-rank primary AUC reduction remains the accepted finding, with its mismatched interval only narrowly excluding chance. Its secondary rank-score interval includes chance. Uncertain gated/A1 changes do not establish a difference in methods' sensitivities. Row1 was generated-image conditioning; row2 was the previously frozen random-RGB row. This single mismatch does not isolate correctness from every difference in row statistics, establish a causal mechanism, or demonstrate secrecy or broad resistance to detection.

## Public reproduction

```sh
python -B scripts/build_png_context_addendum.py
```

Run from the public repository using Python with NumPy and Matplotlib (the existing host interpreter is `/home/meow/Documents/repos/llm-rankcloak/.venv/bin/python`). The builder reads public scores, metadata and accepted publication assets only. It does not import model/application code or require model weights, raw contexts, private keys/packets or execution ledgers. It validates all 80 IDs, 20-per-category coverage, source/control pairing, complete score units, arithmetic and exported CSVs, and checks accepted public evidence remains byte-identical.

The PDF is 7.2 × 3.8 inches; SVG text remains editable and PNG is 450 dpi. Horizontal offsets are deterministic functions of frozen group order, not scores. Every category has 20 individual points plus one distinguishable mean diamond. Means/medians are calculated before display rounding. Existing AUCs and intervals are read unchanged for integration, never recomputed by this builder.

New GPU usage: **0 seconds**. No manuscript source existed, so Markdown integration components were created rather than a full paper. Figure PDF rendering/visual inspection and link/number checks are recorded in [inspection.md](inspection.md).
""")
    # Read the actual exports back, not merely the variables used to write them.
    with (OUT/"score_shift_observations.csv").open(newline="") as f:
        exported=list(csv.DictReader(f))
    if len(exported)!=80:raise ValueError("CSV lost observations")
    for old,new in zip(observations,exported):
        if old["artifact_id"]!=new["artifact_id"] or old["matched_control_id"]!=new["matched_control_id"]:
            raise ValueError("CSV identity/pairing changed")
        if float(new["score_change"])!=float(new["row2_mean_surprisal"])-float(new["row1_mean_surprisal"]):
            raise ValueError("CSV score subtraction changed")
    with (OUT/"score_shift_summary.csv").open(newline="") as f:
        for old,new in zip(summary,csv.DictReader(f)):
            for field in ("mean_row1","mean_row2","mean_score_change","median_score_change"):
                if float(new[field])!=old[field]:raise ValueError("CSV summary changed")
    after=snapshot_public_evidence()
    if before!=after:raise ValueError("accepted public evidence changed")
    try:
        revision=subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True,stderr=subprocess.DEVNULL).strip()
    except (OSError,subprocess.CalledProcessError):revision=None
    outputs=[OUT/n for n in ("README.md","score_shifts.pdf","score_shifts.svg","score_shifts.png",
        "score_shift_observations.csv","score_shift_summary.csv","score_shift_summary.md","caption.md")]
    outputs += [PAPER/"README.md",PAPER/"png_context_detection.md"]
    provenance=dict(schema="png-context-descriptive-addendum-v1",source_revision=revision,
        script=str(Path(__file__).relative_to(ROOT)),script_sha256=digest(__file__),
        inputs_sha256=input_hashes,outputs_sha256={str(p.relative_to(ROOT)):digest(p) for p in outputs},
        score_field=FIELD,units=UNITS,score_change="mismatched row2 minus correct row1",
        analysis="descriptive post hoc; no new tests, intervals, fitting, model execution or observations",
        observation_count=80,independent_payload_groups=20,unique_ordinary_controls=20,
        summary=summary,paired_fixed_minus_control_gap=gap,plotted=plotted,
        plot=dict(size_inches=[7.2,3.8],png_dpi=450,
            offsets="linspace(-0.30, 0.22, 20), frozen group order, identical across categories",
            typography_source="scripts/build_publication_results.py style()/COLORS",
            source_style_sha256=digest(ROOT/"scripts/build_publication_results.py")),
        contexts=manifest["contexts"],
        dependencies=dict(numpy=np.__version__,matplotlib=matplotlib.__version__),
        new_gpu_seconds=0,private_files_and_ledgers_accessed=False,
        historical_accounting_source="artifacts/png_context_detection_review/accounting.json",
        historical_cumulative_gpu_seconds=read(SOURCE/"accounting.json")["cumulative_seconds"],
        checks=dict(all_80_observations=True,all_categories_20=True,groups_and_shared_controls_preserved=True,
            full_2976_channel_scores=True,csv_subtraction_and_summaries_verified=True,
            paired_gap_algebra_verified=True,annotations_from_unrounded_means=True,
            accepted_files_checked=len(before),accepted_evidence_unchanged=True,
            accepted_snapshot_sha256=hashlib.sha256(json.dumps(before,sort_keys=True).encode()).hexdigest(),
            figure_text_within_canvas=True))
    write(OUT/"provenance.json",json.dumps(provenance,indent=2,ensure_ascii=False,allow_nan=False)+"\n")
    print(table)
    print("Paired fixed/control gap:",gap)
    print("Preserved accepted public files:",len(before),"; new GPU seconds: 0")


if __name__=="__main__":
    main()
